// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(openspd_ffiFFI)
import openspd_ffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_openspd_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_openspd_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDouble: FfiConverterPrimitive {
    typealias FfiType = Double
    typealias SwiftType = Double

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Double {
        return try lift(readDouble(&buf))
    }

    public static func write(_ value: Double, into buf: inout [UInt8]) {
        writeDouble(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




/**
 * Perfil carga-velocidad individual (objeto con estado inmutable).
 */
public protocol LvpProtocol : AnyObject {
    
    func exercise()  -> String
    
    func intercept()  -> Double
    
    func isValid()  -> Bool
    
    /**
     * Carga estimada (kg) para una velocidad media dada.
     */
    func loadForVelocity(v: Double)  -> Double
    
    func oneRmKg()  -> Double
    
    /**
     * %1RM correspondiente a una velocidad media.
     */
    func pct1rm(velocity: Double)  -> Double
    
    func points()  -> [Point]
    
    func r2()  -> Double
    
    func slope()  -> Double
    
    /**
     * Serializa el perfil a texto (para persistirlo con los medios de la plataforma).
     */
    func toText()  -> String
    
    func v1rm()  -> Double
    
    /**
     * Velocidad media esperada a un %1RM dado.
     */
    func velocityForPct(pct: Double)  -> Double
    
}

/**
 * Perfil carga-velocidad individual (objeto con estado inmutable).
 */
open class Lvp:
    LvpProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_openspd_ffi_fn_clone_lvp(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_openspd_ffi_fn_free_lvp(pointer, $0) }
    }

    

    
open func exercise() -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_openspd_ffi_fn_method_lvp_exercise(self.uniffiClonePointer(),$0
    )
})
}
    
open func intercept() -> Double {
    return try!  FfiConverterDouble.lift(try! rustCall() {
    uniffi_openspd_ffi_fn_method_lvp_intercept(self.uniffiClonePointer(),$0
    )
})
}
    
open func isValid() -> Bool {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_openspd_ffi_fn_method_lvp_is_valid(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Carga estimada (kg) para una velocidad media dada.
     */
open func loadForVelocity(v: Double) -> Double {
    return try!  FfiConverterDouble.lift(try! rustCall() {
    uniffi_openspd_ffi_fn_method_lvp_load_for_velocity(self.uniffiClonePointer(),
        FfiConverterDouble.lower(v),$0
    )
})
}
    
open func oneRmKg() -> Double {
    return try!  FfiConverterDouble.lift(try! rustCall() {
    uniffi_openspd_ffi_fn_method_lvp_one_rm_kg(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * %1RM correspondiente a una velocidad media.
     */
open func pct1rm(velocity: Double) -> Double {
    return try!  FfiConverterDouble.lift(try! rustCall() {
    uniffi_openspd_ffi_fn_method_lvp_pct_1rm(self.uniffiClonePointer(),
        FfiConverterDouble.lower(velocity),$0
    )
})
}
    
open func points() -> [Point] {
    return try!  FfiConverterSequenceTypePoint.lift(try! rustCall() {
    uniffi_openspd_ffi_fn_method_lvp_points(self.uniffiClonePointer(),$0
    )
})
}
    
open func r2() -> Double {
    return try!  FfiConverterDouble.lift(try! rustCall() {
    uniffi_openspd_ffi_fn_method_lvp_r2(self.uniffiClonePointer(),$0
    )
})
}
    
open func slope() -> Double {
    return try!  FfiConverterDouble.lift(try! rustCall() {
    uniffi_openspd_ffi_fn_method_lvp_slope(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Serializa el perfil a texto (para persistirlo con los medios de la plataforma).
     */
open func toText() -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_openspd_ffi_fn_method_lvp_to_text(self.uniffiClonePointer(),$0
    )
})
}
    
open func v1rm() -> Double {
    return try!  FfiConverterDouble.lift(try! rustCall() {
    uniffi_openspd_ffi_fn_method_lvp_v1rm(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Velocidad media esperada a un %1RM dado.
     */
open func velocityForPct(pct: Double) -> Double {
    return try!  FfiConverterDouble.lift(try! rustCall() {
    uniffi_openspd_ffi_fn_method_lvp_velocity_for_pct(self.uniffiClonePointer(),
        FfiConverterDouble.lower(pct),$0
    )
})
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeLvp: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = Lvp

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> Lvp {
        return Lvp(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: Lvp) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Lvp {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: Lvp, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLvp_lift(_ pointer: UnsafeMutableRawPointer) throws -> Lvp {
    return try FfiConverterTypeLvp.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLvp_lower(_ value: Lvp) -> UnsafeMutableRawPointer {
    return FfiConverterTypeLvp.lower(value)
}




/**
 * Reensamblador con estado: la app móvil le pasa los bytes cifrados de cada notificación BLE y
 * recibe las repeticiones completas ya descifradas y parseadas.
 */
public protocol ReassemblerProtocol : AnyObject {
    
    /**
     * Procesa una notificación cifrada y devuelve las repeticiones completas formadas.
     */
    func push(ciphertext: Data)  -> [EncoderV2Rep]
    
}

/**
 * Reensamblador con estado: la app móvil le pasa los bytes cifrados de cada notificación BLE y
 * recibe las repeticiones completas ya descifradas y parseadas.
 */
open class Reassembler:
    ReassemblerProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_openspd_ffi_fn_clone_reassembler(self.pointer, $0) }
    }
    /**
     * Crea un reensamblador con la clave AES de la sesión (16 bytes, de [`SessionKey::aes_key`]).
     */
public convenience init(aesKey: Data) {
    let pointer =
        try! rustCall() {
    uniffi_openspd_ffi_fn_constructor_reassembler_new(
        FfiConverterData.lower(aesKey),$0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_openspd_ffi_fn_free_reassembler(pointer, $0) }
    }

    

    
    /**
     * Procesa una notificación cifrada y devuelve las repeticiones completas formadas.
     */
open func push(ciphertext: Data) -> [EncoderV2Rep] {
    return try!  FfiConverterSequenceTypeEncoderV2Rep.lift(try! rustCall() {
    uniffi_openspd_ffi_fn_method_reassembler_push(self.uniffiClonePointer(),
        FfiConverterData.lower(ciphertext),$0
    )
})
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeReassembler: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = Reassembler

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> Reassembler {
        return Reassembler(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: Reassembler) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Reassembler {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: Reassembler, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeReassembler_lift(_ pointer: UnsafeMutableRawPointer) throws -> Reassembler {
    return try FfiConverterTypeReassembler.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeReassembler_lower(_ value: Reassembler) -> UnsafeMutableRawPointer {
    return FfiConverterTypeReassembler.lower(value)
}


/**
 * Repetición completa del encoder v2 (ambas fases, aceleraciones).
 */
public struct EncoderV2Rep {
    public var rep: UInt32
    public var phase: Phase
    public var mpv: Double
    public var rom: Double
    public var peakVelocity: Double
    public var avgVelocity: Double
    public var maxAccel: Double
    public var avgAccel: Double

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(rep: UInt32, phase: Phase, mpv: Double, rom: Double, peakVelocity: Double, avgVelocity: Double, maxAccel: Double, avgAccel: Double) {
        self.rep = rep
        self.phase = phase
        self.mpv = mpv
        self.rom = rom
        self.peakVelocity = peakVelocity
        self.avgVelocity = avgVelocity
        self.maxAccel = maxAccel
        self.avgAccel = avgAccel
    }
}



extension EncoderV2Rep: Equatable, Hashable {
    public static func ==(lhs: EncoderV2Rep, rhs: EncoderV2Rep) -> Bool {
        if lhs.rep != rhs.rep {
            return false
        }
        if lhs.phase != rhs.phase {
            return false
        }
        if lhs.mpv != rhs.mpv {
            return false
        }
        if lhs.rom != rhs.rom {
            return false
        }
        if lhs.peakVelocity != rhs.peakVelocity {
            return false
        }
        if lhs.avgVelocity != rhs.avgVelocity {
            return false
        }
        if lhs.maxAccel != rhs.maxAccel {
            return false
        }
        if lhs.avgAccel != rhs.avgAccel {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(rep)
        hasher.combine(phase)
        hasher.combine(mpv)
        hasher.combine(rom)
        hasher.combine(peakVelocity)
        hasher.combine(avgVelocity)
        hasher.combine(maxAccel)
        hasher.combine(avgAccel)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEncoderV2Rep: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EncoderV2Rep {
        return
            try EncoderV2Rep(
                rep: FfiConverterUInt32.read(from: &buf), 
                phase: FfiConverterTypePhase.read(from: &buf), 
                mpv: FfiConverterDouble.read(from: &buf), 
                rom: FfiConverterDouble.read(from: &buf), 
                peakVelocity: FfiConverterDouble.read(from: &buf), 
                avgVelocity: FfiConverterDouble.read(from: &buf), 
                maxAccel: FfiConverterDouble.read(from: &buf), 
                avgAccel: FfiConverterDouble.read(from: &buf)
        )
    }

    public static func write(_ value: EncoderV2Rep, into buf: inout [UInt8]) {
        FfiConverterUInt32.write(value.rep, into: &buf)
        FfiConverterTypePhase.write(value.phase, into: &buf)
        FfiConverterDouble.write(value.mpv, into: &buf)
        FfiConverterDouble.write(value.rom, into: &buf)
        FfiConverterDouble.write(value.peakVelocity, into: &buf)
        FfiConverterDouble.write(value.avgVelocity, into: &buf)
        FfiConverterDouble.write(value.maxAccel, into: &buf)
        FfiConverterDouble.write(value.avgAccel, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEncoderV2Rep_lift(_ buf: RustBuffer) throws -> EncoderV2Rep {
    return try FfiConverterTypeEncoderV2Rep.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEncoderV2Rep_lower(_ value: EncoderV2Rep) -> RustBuffer {
    return FfiConverterTypeEncoderV2Rep.lower(value)
}


/**
 * Un punto del perfil carga-velocidad.
 */
public struct Point {
    public var loadKg: Double
    public var bestVelocity: Double

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(loadKg: Double, bestVelocity: Double) {
        self.loadKg = loadKg
        self.bestVelocity = bestVelocity
    }
}



extension Point: Equatable, Hashable {
    public static func ==(lhs: Point, rhs: Point) -> Bool {
        if lhs.loadKg != rhs.loadKg {
            return false
        }
        if lhs.bestVelocity != rhs.bestVelocity {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(loadKg)
        hasher.combine(bestVelocity)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePoint: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Point {
        return
            try Point(
                loadKg: FfiConverterDouble.read(from: &buf), 
                bestVelocity: FfiConverterDouble.read(from: &buf)
        )
    }

    public static func write(_ value: Point, into buf: inout [UInt8]) {
        FfiConverterDouble.write(value.loadKg, into: &buf)
        FfiConverterDouble.write(value.bestVelocity, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePoint_lift(_ buf: RustBuffer) throws -> Point {
    return try FfiConverterTypePoint.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePoint_lower(_ value: Point) -> RustBuffer {
    return FfiConverterTypePoint.lower(value)
}


/**
 * Una repetición decodificada (modelo común v1/v2).
 */
public struct Rep {
    public var rep: UInt32
    public var meanVelocity: Double
    public var rom: Double
    public var peakVelocity: Double

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(rep: UInt32, meanVelocity: Double, rom: Double, peakVelocity: Double) {
        self.rep = rep
        self.meanVelocity = meanVelocity
        self.rom = rom
        self.peakVelocity = peakVelocity
    }
}



extension Rep: Equatable, Hashable {
    public static func ==(lhs: Rep, rhs: Rep) -> Bool {
        if lhs.rep != rhs.rep {
            return false
        }
        if lhs.meanVelocity != rhs.meanVelocity {
            return false
        }
        if lhs.rom != rhs.rom {
            return false
        }
        if lhs.peakVelocity != rhs.peakVelocity {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(rep)
        hasher.combine(meanVelocity)
        hasher.combine(rom)
        hasher.combine(peakVelocity)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRep: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Rep {
        return
            try Rep(
                rep: FfiConverterUInt32.read(from: &buf), 
                meanVelocity: FfiConverterDouble.read(from: &buf), 
                rom: FfiConverterDouble.read(from: &buf), 
                peakVelocity: FfiConverterDouble.read(from: &buf)
        )
    }

    public static func write(_ value: Rep, into buf: inout [UInt8]) {
        FfiConverterUInt32.write(value.rep, into: &buf)
        FfiConverterDouble.write(value.meanVelocity, into: &buf)
        FfiConverterDouble.write(value.rom, into: &buf)
        FfiConverterDouble.write(value.peakVelocity, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRep_lift(_ buf: RustBuffer) throws -> Rep {
    return try FfiConverterTypeRep.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRep_lower(_ value: Rep) -> RustBuffer {
    return FfiConverterTypeRep.lower(value)
}


/**
 * Llave de sesión del encoder v2: escribe `unlock_bytes` en la característica de desbloqueo y usa
 * `aes_key` para crear el [`Reassembler`].
 */
public struct SessionKey {
    public var unlockBytes: Data
    public var aesKey: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(unlockBytes: Data, aesKey: Data) {
        self.unlockBytes = unlockBytes
        self.aesKey = aesKey
    }
}



extension SessionKey: Equatable, Hashable {
    public static func ==(lhs: SessionKey, rhs: SessionKey) -> Bool {
        if lhs.unlockBytes != rhs.unlockBytes {
            return false
        }
        if lhs.aesKey != rhs.aesKey {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(unlockBytes)
        hasher.combine(aesKey)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSessionKey: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SessionKey {
        return
            try SessionKey(
                unlockBytes: FfiConverterData.read(from: &buf), 
                aesKey: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: SessionKey, into buf: inout [UInt8]) {
        FfiConverterData.write(value.unlockBytes, into: &buf)
        FfiConverterData.write(value.aesKey, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSessionKey_lift(_ buf: RustBuffer) throws -> SessionKey {
    return try FfiConverterTypeSessionKey.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSessionKey_lower(_ value: SessionKey) -> RustBuffer {
    return FfiConverterTypeSessionKey.lower(value)
}


/**
 * Resumen de una serie.
 */
public struct SetSummary {
    public var nReps: UInt32
    public var bestMeanVelocity: Double
    public var lastMeanVelocity: Double
    public var avgMeanVelocity: Double
    public var peakVelocity: Double
    public var avgRom: Double
    public var velocityLossPct: Double

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(nReps: UInt32, bestMeanVelocity: Double, lastMeanVelocity: Double, avgMeanVelocity: Double, peakVelocity: Double, avgRom: Double, velocityLossPct: Double) {
        self.nReps = nReps
        self.bestMeanVelocity = bestMeanVelocity
        self.lastMeanVelocity = lastMeanVelocity
        self.avgMeanVelocity = avgMeanVelocity
        self.peakVelocity = peakVelocity
        self.avgRom = avgRom
        self.velocityLossPct = velocityLossPct
    }
}



extension SetSummary: Equatable, Hashable {
    public static func ==(lhs: SetSummary, rhs: SetSummary) -> Bool {
        if lhs.nReps != rhs.nReps {
            return false
        }
        if lhs.bestMeanVelocity != rhs.bestMeanVelocity {
            return false
        }
        if lhs.lastMeanVelocity != rhs.lastMeanVelocity {
            return false
        }
        if lhs.avgMeanVelocity != rhs.avgMeanVelocity {
            return false
        }
        if lhs.peakVelocity != rhs.peakVelocity {
            return false
        }
        if lhs.avgRom != rhs.avgRom {
            return false
        }
        if lhs.velocityLossPct != rhs.velocityLossPct {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(nReps)
        hasher.combine(bestMeanVelocity)
        hasher.combine(lastMeanVelocity)
        hasher.combine(avgMeanVelocity)
        hasher.combine(peakVelocity)
        hasher.combine(avgRom)
        hasher.combine(velocityLossPct)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSetSummary: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SetSummary {
        return
            try SetSummary(
                nReps: FfiConverterUInt32.read(from: &buf), 
                bestMeanVelocity: FfiConverterDouble.read(from: &buf), 
                lastMeanVelocity: FfiConverterDouble.read(from: &buf), 
                avgMeanVelocity: FfiConverterDouble.read(from: &buf), 
                peakVelocity: FfiConverterDouble.read(from: &buf), 
                avgRom: FfiConverterDouble.read(from: &buf), 
                velocityLossPct: FfiConverterDouble.read(from: &buf)
        )
    }

    public static func write(_ value: SetSummary, into buf: inout [UInt8]) {
        FfiConverterUInt32.write(value.nReps, into: &buf)
        FfiConverterDouble.write(value.bestMeanVelocity, into: &buf)
        FfiConverterDouble.write(value.lastMeanVelocity, into: &buf)
        FfiConverterDouble.write(value.avgMeanVelocity, into: &buf)
        FfiConverterDouble.write(value.peakVelocity, into: &buf)
        FfiConverterDouble.write(value.avgRom, into: &buf)
        FfiConverterDouble.write(value.velocityLossPct, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSetSummary_lift(_ buf: RustBuffer) throws -> SetSummary {
    return try FfiConverterTypeSetSummary.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSetSummary_lower(_ value: SetSummary) -> RustBuffer {
    return FfiConverterTypeSetSummary.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Fase de una repetición del encoder v2.
 */

public enum Phase {
    
    case concentric
    case eccentric
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePhase: FfiConverterRustBuffer {
    typealias SwiftType = Phase

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Phase {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .concentric
        
        case 2: return .eccentric
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: Phase, into buf: inout [UInt8]) {
        switch value {
        
        
        case .concentric:
            writeInt(&buf, Int32(1))
        
        
        case .eccentric:
            writeInt(&buf, Int32(2))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePhase_lift(_ buf: RustBuffer) throws -> Phase {
    return try FfiConverterTypePhase.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePhase_lower(_ value: Phase) -> RustBuffer {
    return FfiConverterTypePhase.lower(value)
}



extension Phase: Equatable, Hashable {}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionDouble: FfiConverterRustBuffer {
    typealias SwiftType = Double?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterDouble.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterDouble.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeLvp: FfiConverterRustBuffer {
    typealias SwiftType = Lvp?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeLvp.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeLvp.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeEncoderV2Rep: FfiConverterRustBuffer {
    typealias SwiftType = EncoderV2Rep?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeEncoderV2Rep.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeEncoderV2Rep.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeRep: FfiConverterRustBuffer {
    typealias SwiftType = Rep?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeRep.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeRep.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeSetSummary: FfiConverterRustBuffer {
    typealias SwiftType = SetSummary?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeSetSummary.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeSetSummary.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeEncoderV2Rep: FfiConverterRustBuffer {
    typealias SwiftType = [EncoderV2Rep]

    public static func write(_ value: [EncoderV2Rep], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeEncoderV2Rep.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [EncoderV2Rep] {
        let len: Int32 = try readInt(&buf)
        var seq = [EncoderV2Rep]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeEncoderV2Rep.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypePoint: FfiConverterRustBuffer {
    typealias SwiftType = [Point]

    public static func write(_ value: [Point], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypePoint.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Point] {
        let len: Int32 = try readInt(&buf)
        var seq = [Point]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypePoint.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeRep: FfiConverterRustBuffer {
    typealias SwiftType = [Rep]

    public static func write(_ value: [Rep], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeRep.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Rep] {
        let len: Int32 = try readInt(&buf)
        var seq = [Rep]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeRep.read(from: &buf))
        }
        return seq
    }
}
/**
 * Comando de inicio de serie del encoder v2.
 */
public func beginCommand(rom: UInt32, eccentric: Bool, metric: String) -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_openspd_ffi_fn_func_begin_command(
        FfiConverterUInt32.lower(rom),
        FfiConverterBool.lower(eccentric),
        FfiConverterString.lower(metric),$0
    )
})
}
/**
 * Umbral de velocidad al 1RM por defecto para un ejercicio.
 */
public func defaultV1rm(exercise: String) -> Double {
    return try!  FfiConverterDouble.lift(try! rustCall() {
    uniffi_openspd_ffi_fn_func_default_v1rm(
        FfiConverterString.lower(exercise),$0
    )
})
}
/**
 * Convierte una rep v2 al modelo común `Rep` (usa MPV como velocidad media).
 */
public func encoderV2ToRep(rep: EncoderV2Rep) -> Rep {
    return try!  FfiConverterTypeRep.lift(try! rustCall() {
    uniffi_openspd_ffi_fn_func_encoder_v2_to_rep(
        FfiConverterTypeEncoderV2Rep.lower(rep),$0
    )
})
}
/**
 * 1RM (kg) a partir de la carga usada y el %1RM correspondiente. `None` si %1RM <= 0.
 */
public func est1rmKg(loadKg: Double, pct1rm: Double) -> Double? {
    return try!  FfiConverterOptionDouble.lift(try! rustCall() {
    uniffi_openspd_ffi_fn_func_est_1rm_kg(
        FfiConverterDouble.lower(loadKg),
        FfiConverterDouble.lower(pct1rm),$0
    )
})
}
/**
 * %1RM estimado por ecuación poblacional. `None` si el ejercicio no tiene ecuación.
 */
public func est1rmPct(exercise: String, meanVelocity: Double) -> Double? {
    return try!  FfiConverterOptionDouble.lift(try! rustCall() {
    uniffi_openspd_ffi_fn_func_est_1rm_pct(
        FfiConverterString.lower(exercise),
        FfiConverterDouble.lower(meanVelocity),$0
    )
})
}
/**
 * Genera una llave de sesión nueva para el encoder v2.
 */
public func generateKey() -> SessionKey {
    return try!  FfiConverterTypeSessionKey.lift(try! rustCall() {
    uniffi_openspd_ffi_fn_func_generate_key($0
    )
})
}
/**
 * Zona de carga orientativa según la velocidad media.
 */
public func loadZone(meanVelocity: Double) -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_openspd_ffi_fn_func_load_zone(
        FfiConverterDouble.lower(meanVelocity),$0
    )
})
}
/**
 * Ajusta un perfil carga-velocidad. `None` si hay <2 cargas distintas.
 */
public func lvpFit(exercise: String, points: [Point], v1rm: Double) -> Lvp? {
    return try!  FfiConverterOptionTypeLvp.lift(try! rustCall() {
    uniffi_openspd_ffi_fn_func_lvp_fit(
        FfiConverterString.lower(exercise),
        FfiConverterSequenceTypePoint.lower(points),
        FfiConverterDouble.lower(v1rm),$0
    )
})
}
/**
 * Reconstruye un perfil desde su texto serializado (`Lvp::to_text`). `None` si es inválido.
 */
public func lvpFromText(text: String) -> Lvp? {
    return try!  FfiConverterOptionTypeLvp.lift(try! rustCall() {
    uniffi_openspd_ffi_fn_func_lvp_from_text(
        FfiConverterString.lower(text),$0
    )
})
}
/**
 * Parsea una línea cruda del encoder v1 (WiFi). `None` si no encaja con el formato.
 */
public func parseLine(line: String) -> Rep? {
    return try!  FfiConverterOptionTypeRep.lift(try! rustCall() {
    uniffi_openspd_ffi_fn_func_parse_line(
        FfiConverterString.lower(line),$0
    )
})
}
/**
 * Parsea el texto plano de una repetición v2 (`@...&`).
 */
public func parseRepetition(s: String) -> EncoderV2Rep? {
    return try!  FfiConverterOptionTypeEncoderV2Rep.lift(try! rustCall() {
    uniffi_openspd_ffi_fn_func_parse_repetition(
        FfiConverterString.lower(s),$0
    )
})
}
/**
 * Resumen de una serie. `None` si no hay reps.
 */
public func summarize(reps: [Rep]) -> SetSummary? {
    return try!  FfiConverterOptionTypeSetSummary.lift(try! rustCall() {
    uniffi_openspd_ffi_fn_func_summarize(
        FfiConverterSequenceTypeRep.lower(reps),$0
    )
})
}
/**
 * % de pérdida de velocidad respecto a la mejor rep de la serie.
 */
public func velocityLoss(reps: [Rep]) -> Double {
    return try!  FfiConverterDouble.lift(try! rustCall() {
    uniffi_openspd_ffi_fn_func_velocity_loss(
        FfiConverterSequenceTypeRep.lower(reps),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_openspd_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_openspd_ffi_checksum_func_begin_command() != 7403) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openspd_ffi_checksum_func_default_v1rm() != 37702) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openspd_ffi_checksum_func_encoder_v2_to_rep() != 31825) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openspd_ffi_checksum_func_est_1rm_kg() != 15655) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openspd_ffi_checksum_func_est_1rm_pct() != 1376) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openspd_ffi_checksum_func_generate_key() != 9225) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openspd_ffi_checksum_func_load_zone() != 46954) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openspd_ffi_checksum_func_lvp_fit() != 3402) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openspd_ffi_checksum_func_lvp_from_text() != 63640) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openspd_ffi_checksum_func_parse_line() != 20757) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openspd_ffi_checksum_func_parse_repetition() != 40086) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openspd_ffi_checksum_func_summarize() != 14872) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openspd_ffi_checksum_func_velocity_loss() != 60794) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openspd_ffi_checksum_method_lvp_exercise() != 6880) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openspd_ffi_checksum_method_lvp_intercept() != 64962) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openspd_ffi_checksum_method_lvp_is_valid() != 34399) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openspd_ffi_checksum_method_lvp_load_for_velocity() != 32493) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openspd_ffi_checksum_method_lvp_one_rm_kg() != 23961) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openspd_ffi_checksum_method_lvp_pct_1rm() != 29886) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openspd_ffi_checksum_method_lvp_points() != 26037) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openspd_ffi_checksum_method_lvp_r2() != 14555) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openspd_ffi_checksum_method_lvp_slope() != 1499) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openspd_ffi_checksum_method_lvp_to_text() != 47154) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openspd_ffi_checksum_method_lvp_v1rm() != 48103) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openspd_ffi_checksum_method_lvp_velocity_for_pct() != 20051) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openspd_ffi_checksum_method_reassembler_push() != 50507) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_openspd_ffi_checksum_constructor_reassembler_new() != 32775) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all