// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
    // We also try to prevent mixing versions of shared uniffi header structs.
    // If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V4
    #ifndef UNIFFI_SHARED_HEADER_V4
        #error Combining helper code from multiple versions of uniffi is not supported
    #endif // ndef UNIFFI_SHARED_HEADER_V4
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V4
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️

typedef struct RustBuffer
{
    uint64_t capacity;
    uint64_t len;
    uint8_t *_Nullable data;
} RustBuffer;

typedef struct ForeignBytes
{
    int32_t len;
    const uint8_t *_Nullable data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
    int8_t code;
    RustBuffer errorBuf;
} RustCallStatus;

// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H
#ifndef UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
#define UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
typedef void (*UniffiRustFutureContinuationCallback)(uint64_t, int8_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
typedef void (*UniffiForeignFutureFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
typedef void (*UniffiCallbackInterfaceFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE
typedef struct UniffiForeignFuture {
    uint64_t handle;
    UniffiForeignFutureFree _Nonnull free;
} UniffiForeignFuture;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
typedef struct UniffiForeignFutureStructU8 {
    uint8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
typedef void (*UniffiForeignFutureCompleteU8)(uint64_t, UniffiForeignFutureStructU8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
typedef struct UniffiForeignFutureStructI8 {
    int8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
typedef void (*UniffiForeignFutureCompleteI8)(uint64_t, UniffiForeignFutureStructI8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
typedef struct UniffiForeignFutureStructU16 {
    uint16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
typedef void (*UniffiForeignFutureCompleteU16)(uint64_t, UniffiForeignFutureStructU16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
typedef struct UniffiForeignFutureStructI16 {
    int16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
typedef void (*UniffiForeignFutureCompleteI16)(uint64_t, UniffiForeignFutureStructI16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
typedef struct UniffiForeignFutureStructU32 {
    uint32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
typedef void (*UniffiForeignFutureCompleteU32)(uint64_t, UniffiForeignFutureStructU32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
typedef struct UniffiForeignFutureStructI32 {
    int32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
typedef void (*UniffiForeignFutureCompleteI32)(uint64_t, UniffiForeignFutureStructI32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
typedef struct UniffiForeignFutureStructU64 {
    uint64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
typedef void (*UniffiForeignFutureCompleteU64)(uint64_t, UniffiForeignFutureStructU64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
typedef struct UniffiForeignFutureStructI64 {
    int64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
typedef void (*UniffiForeignFutureCompleteI64)(uint64_t, UniffiForeignFutureStructI64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
typedef struct UniffiForeignFutureStructF32 {
    float returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
typedef void (*UniffiForeignFutureCompleteF32)(uint64_t, UniffiForeignFutureStructF32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
typedef struct UniffiForeignFutureStructF64 {
    double returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
typedef void (*UniffiForeignFutureCompleteF64)(uint64_t, UniffiForeignFutureStructF64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
typedef struct UniffiForeignFutureStructPointer {
    void*_Nonnull returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructPointer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
typedef void (*UniffiForeignFutureCompletePointer)(uint64_t, UniffiForeignFutureStructPointer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
typedef struct UniffiForeignFutureStructRustBuffer {
    RustBuffer returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructRustBuffer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
typedef void (*UniffiForeignFutureCompleteRustBuffer)(uint64_t, UniffiForeignFutureStructRustBuffer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
typedef struct UniffiForeignFutureStructVoid {
    RustCallStatus callStatus;
} UniffiForeignFutureStructVoid;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
typedef void (*UniffiForeignFutureCompleteVoid)(uint64_t, UniffiForeignFutureStructVoid
    );

#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_FN_CLONE_LVP
#define UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_FN_CLONE_LVP
void*_Nonnull uniffi_openspd_ffi_fn_clone_lvp(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_FN_FREE_LVP
#define UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_FN_FREE_LVP
void uniffi_openspd_ffi_fn_free_lvp(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_FN_METHOD_LVP_EXERCISE
#define UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_FN_METHOD_LVP_EXERCISE
RustBuffer uniffi_openspd_ffi_fn_method_lvp_exercise(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_FN_METHOD_LVP_INTERCEPT
#define UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_FN_METHOD_LVP_INTERCEPT
double uniffi_openspd_ffi_fn_method_lvp_intercept(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_FN_METHOD_LVP_IS_VALID
#define UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_FN_METHOD_LVP_IS_VALID
int8_t uniffi_openspd_ffi_fn_method_lvp_is_valid(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_FN_METHOD_LVP_LOAD_FOR_VELOCITY
#define UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_FN_METHOD_LVP_LOAD_FOR_VELOCITY
double uniffi_openspd_ffi_fn_method_lvp_load_for_velocity(void*_Nonnull ptr, double v, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_FN_METHOD_LVP_ONE_RM_KG
#define UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_FN_METHOD_LVP_ONE_RM_KG
double uniffi_openspd_ffi_fn_method_lvp_one_rm_kg(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_FN_METHOD_LVP_PCT_1RM
#define UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_FN_METHOD_LVP_PCT_1RM
double uniffi_openspd_ffi_fn_method_lvp_pct_1rm(void*_Nonnull ptr, double velocity, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_FN_METHOD_LVP_POINTS
#define UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_FN_METHOD_LVP_POINTS
RustBuffer uniffi_openspd_ffi_fn_method_lvp_points(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_FN_METHOD_LVP_R2
#define UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_FN_METHOD_LVP_R2
double uniffi_openspd_ffi_fn_method_lvp_r2(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_FN_METHOD_LVP_SLOPE
#define UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_FN_METHOD_LVP_SLOPE
double uniffi_openspd_ffi_fn_method_lvp_slope(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_FN_METHOD_LVP_TO_TEXT
#define UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_FN_METHOD_LVP_TO_TEXT
RustBuffer uniffi_openspd_ffi_fn_method_lvp_to_text(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_FN_METHOD_LVP_V1RM
#define UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_FN_METHOD_LVP_V1RM
double uniffi_openspd_ffi_fn_method_lvp_v1rm(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_FN_METHOD_LVP_VELOCITY_FOR_PCT
#define UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_FN_METHOD_LVP_VELOCITY_FOR_PCT
double uniffi_openspd_ffi_fn_method_lvp_velocity_for_pct(void*_Nonnull ptr, double pct, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_FN_CLONE_REASSEMBLER
#define UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_FN_CLONE_REASSEMBLER
void*_Nonnull uniffi_openspd_ffi_fn_clone_reassembler(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_FN_FREE_REASSEMBLER
#define UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_FN_FREE_REASSEMBLER
void uniffi_openspd_ffi_fn_free_reassembler(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_FN_CONSTRUCTOR_REASSEMBLER_NEW
#define UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_FN_CONSTRUCTOR_REASSEMBLER_NEW
void*_Nonnull uniffi_openspd_ffi_fn_constructor_reassembler_new(RustBuffer aes_key, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_FN_METHOD_REASSEMBLER_PUSH
#define UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_FN_METHOD_REASSEMBLER_PUSH
RustBuffer uniffi_openspd_ffi_fn_method_reassembler_push(void*_Nonnull ptr, RustBuffer ciphertext, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_FN_FUNC_BEGIN_COMMAND
#define UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_FN_FUNC_BEGIN_COMMAND
RustBuffer uniffi_openspd_ffi_fn_func_begin_command(uint32_t rom, int8_t eccentric, RustBuffer metric, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_FN_FUNC_DEFAULT_V1RM
#define UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_FN_FUNC_DEFAULT_V1RM
double uniffi_openspd_ffi_fn_func_default_v1rm(RustBuffer exercise, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_FN_FUNC_ENCODER_V2_TO_REP
#define UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_FN_FUNC_ENCODER_V2_TO_REP
RustBuffer uniffi_openspd_ffi_fn_func_encoder_v2_to_rep(RustBuffer rep, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_FN_FUNC_EST_1RM_KG
#define UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_FN_FUNC_EST_1RM_KG
RustBuffer uniffi_openspd_ffi_fn_func_est_1rm_kg(double load_kg, double pct_1rm, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_FN_FUNC_EST_1RM_PCT
#define UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_FN_FUNC_EST_1RM_PCT
RustBuffer uniffi_openspd_ffi_fn_func_est_1rm_pct(RustBuffer exercise, double mean_velocity, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_FN_FUNC_GENERATE_KEY
#define UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_FN_FUNC_GENERATE_KEY
RustBuffer uniffi_openspd_ffi_fn_func_generate_key(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_FN_FUNC_LOAD_ZONE
#define UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_FN_FUNC_LOAD_ZONE
RustBuffer uniffi_openspd_ffi_fn_func_load_zone(double mean_velocity, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_FN_FUNC_LVP_FIT
#define UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_FN_FUNC_LVP_FIT
RustBuffer uniffi_openspd_ffi_fn_func_lvp_fit(RustBuffer exercise, RustBuffer points, double v1rm, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_FN_FUNC_LVP_FROM_TEXT
#define UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_FN_FUNC_LVP_FROM_TEXT
RustBuffer uniffi_openspd_ffi_fn_func_lvp_from_text(RustBuffer text, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_FN_FUNC_PARSE_LINE
#define UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_FN_FUNC_PARSE_LINE
RustBuffer uniffi_openspd_ffi_fn_func_parse_line(RustBuffer line, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_FN_FUNC_PARSE_REPETITION
#define UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_FN_FUNC_PARSE_REPETITION
RustBuffer uniffi_openspd_ffi_fn_func_parse_repetition(RustBuffer s, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_FN_FUNC_SUMMARIZE
#define UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_FN_FUNC_SUMMARIZE
RustBuffer uniffi_openspd_ffi_fn_func_summarize(RustBuffer reps, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_FN_FUNC_VELOCITY_LOSS
#define UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_FN_FUNC_VELOCITY_LOSS
double uniffi_openspd_ffi_fn_func_velocity_loss(RustBuffer reps, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUSTBUFFER_ALLOC
#define UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUSTBUFFER_ALLOC
RustBuffer ffi_openspd_ffi_rustbuffer_alloc(uint64_t size, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUSTBUFFER_FROM_BYTES
#define UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUSTBUFFER_FROM_BYTES
RustBuffer ffi_openspd_ffi_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUSTBUFFER_FREE
#define UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUSTBUFFER_FREE
void ffi_openspd_ffi_rustbuffer_free(RustBuffer buf, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUSTBUFFER_RESERVE
#define UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUSTBUFFER_RESERVE
RustBuffer ffi_openspd_ffi_rustbuffer_reserve(RustBuffer buf, uint64_t additional, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_POLL_U8
#define UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_POLL_U8
void ffi_openspd_ffi_rust_future_poll_u8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_CANCEL_U8
#define UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_CANCEL_U8
void ffi_openspd_ffi_rust_future_cancel_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_FREE_U8
#define UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_FREE_U8
void ffi_openspd_ffi_rust_future_free_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_COMPLETE_U8
uint8_t ffi_openspd_ffi_rust_future_complete_u8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_POLL_I8
#define UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_POLL_I8
void ffi_openspd_ffi_rust_future_poll_i8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_CANCEL_I8
#define UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_CANCEL_I8
void ffi_openspd_ffi_rust_future_cancel_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_FREE_I8
#define UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_FREE_I8
void ffi_openspd_ffi_rust_future_free_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_COMPLETE_I8
int8_t ffi_openspd_ffi_rust_future_complete_i8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_POLL_U16
#define UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_POLL_U16
void ffi_openspd_ffi_rust_future_poll_u16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_CANCEL_U16
#define UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_CANCEL_U16
void ffi_openspd_ffi_rust_future_cancel_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_FREE_U16
#define UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_FREE_U16
void ffi_openspd_ffi_rust_future_free_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_COMPLETE_U16
uint16_t ffi_openspd_ffi_rust_future_complete_u16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_POLL_I16
#define UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_POLL_I16
void ffi_openspd_ffi_rust_future_poll_i16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_CANCEL_I16
#define UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_CANCEL_I16
void ffi_openspd_ffi_rust_future_cancel_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_FREE_I16
#define UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_FREE_I16
void ffi_openspd_ffi_rust_future_free_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_COMPLETE_I16
int16_t ffi_openspd_ffi_rust_future_complete_i16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_POLL_U32
#define UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_POLL_U32
void ffi_openspd_ffi_rust_future_poll_u32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_CANCEL_U32
#define UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_CANCEL_U32
void ffi_openspd_ffi_rust_future_cancel_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_FREE_U32
#define UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_FREE_U32
void ffi_openspd_ffi_rust_future_free_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_COMPLETE_U32
uint32_t ffi_openspd_ffi_rust_future_complete_u32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_POLL_I32
#define UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_POLL_I32
void ffi_openspd_ffi_rust_future_poll_i32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_CANCEL_I32
#define UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_CANCEL_I32
void ffi_openspd_ffi_rust_future_cancel_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_FREE_I32
#define UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_FREE_I32
void ffi_openspd_ffi_rust_future_free_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_COMPLETE_I32
int32_t ffi_openspd_ffi_rust_future_complete_i32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_POLL_U64
#define UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_POLL_U64
void ffi_openspd_ffi_rust_future_poll_u64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_CANCEL_U64
#define UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_CANCEL_U64
void ffi_openspd_ffi_rust_future_cancel_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_FREE_U64
#define UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_FREE_U64
void ffi_openspd_ffi_rust_future_free_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_COMPLETE_U64
uint64_t ffi_openspd_ffi_rust_future_complete_u64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_POLL_I64
#define UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_POLL_I64
void ffi_openspd_ffi_rust_future_poll_i64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_CANCEL_I64
#define UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_CANCEL_I64
void ffi_openspd_ffi_rust_future_cancel_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_FREE_I64
#define UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_FREE_I64
void ffi_openspd_ffi_rust_future_free_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_COMPLETE_I64
int64_t ffi_openspd_ffi_rust_future_complete_i64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_POLL_F32
#define UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_POLL_F32
void ffi_openspd_ffi_rust_future_poll_f32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_CANCEL_F32
#define UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_CANCEL_F32
void ffi_openspd_ffi_rust_future_cancel_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_FREE_F32
#define UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_FREE_F32
void ffi_openspd_ffi_rust_future_free_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_COMPLETE_F32
float ffi_openspd_ffi_rust_future_complete_f32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_POLL_F64
#define UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_POLL_F64
void ffi_openspd_ffi_rust_future_poll_f64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_CANCEL_F64
#define UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_CANCEL_F64
void ffi_openspd_ffi_rust_future_cancel_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_FREE_F64
#define UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_FREE_F64
void ffi_openspd_ffi_rust_future_free_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_COMPLETE_F64
double ffi_openspd_ffi_rust_future_complete_f64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_POLL_POINTER
#define UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_POLL_POINTER
void ffi_openspd_ffi_rust_future_poll_pointer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_CANCEL_POINTER
#define UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_CANCEL_POINTER
void ffi_openspd_ffi_rust_future_cancel_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_FREE_POINTER
#define UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_FREE_POINTER
void ffi_openspd_ffi_rust_future_free_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_COMPLETE_POINTER
void*_Nonnull ffi_openspd_ffi_rust_future_complete_pointer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_POLL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_POLL_RUST_BUFFER
void ffi_openspd_ffi_rust_future_poll_rust_buffer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_CANCEL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_CANCEL_RUST_BUFFER
void ffi_openspd_ffi_rust_future_cancel_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_FREE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_FREE_RUST_BUFFER
void ffi_openspd_ffi_rust_future_free_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_COMPLETE_RUST_BUFFER
RustBuffer ffi_openspd_ffi_rust_future_complete_rust_buffer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_POLL_VOID
#define UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_POLL_VOID
void ffi_openspd_ffi_rust_future_poll_void(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_CANCEL_VOID
#define UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_CANCEL_VOID
void ffi_openspd_ffi_rust_future_cancel_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_FREE_VOID
#define UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_FREE_VOID
void ffi_openspd_ffi_rust_future_free_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FFI_OPENSPD_FFI_RUST_FUTURE_COMPLETE_VOID
void ffi_openspd_ffi_rust_future_complete_void(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_CHECKSUM_FUNC_BEGIN_COMMAND
#define UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_CHECKSUM_FUNC_BEGIN_COMMAND
uint16_t uniffi_openspd_ffi_checksum_func_begin_command(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_CHECKSUM_FUNC_DEFAULT_V1RM
#define UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_CHECKSUM_FUNC_DEFAULT_V1RM
uint16_t uniffi_openspd_ffi_checksum_func_default_v1rm(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_CHECKSUM_FUNC_ENCODER_V2_TO_REP
#define UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_CHECKSUM_FUNC_ENCODER_V2_TO_REP
uint16_t uniffi_openspd_ffi_checksum_func_encoder_v2_to_rep(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_CHECKSUM_FUNC_EST_1RM_KG
#define UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_CHECKSUM_FUNC_EST_1RM_KG
uint16_t uniffi_openspd_ffi_checksum_func_est_1rm_kg(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_CHECKSUM_FUNC_EST_1RM_PCT
#define UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_CHECKSUM_FUNC_EST_1RM_PCT
uint16_t uniffi_openspd_ffi_checksum_func_est_1rm_pct(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_CHECKSUM_FUNC_GENERATE_KEY
#define UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_CHECKSUM_FUNC_GENERATE_KEY
uint16_t uniffi_openspd_ffi_checksum_func_generate_key(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_CHECKSUM_FUNC_LOAD_ZONE
#define UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_CHECKSUM_FUNC_LOAD_ZONE
uint16_t uniffi_openspd_ffi_checksum_func_load_zone(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_CHECKSUM_FUNC_LVP_FIT
#define UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_CHECKSUM_FUNC_LVP_FIT
uint16_t uniffi_openspd_ffi_checksum_func_lvp_fit(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_CHECKSUM_FUNC_LVP_FROM_TEXT
#define UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_CHECKSUM_FUNC_LVP_FROM_TEXT
uint16_t uniffi_openspd_ffi_checksum_func_lvp_from_text(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_CHECKSUM_FUNC_PARSE_LINE
#define UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_CHECKSUM_FUNC_PARSE_LINE
uint16_t uniffi_openspd_ffi_checksum_func_parse_line(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_CHECKSUM_FUNC_PARSE_REPETITION
#define UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_CHECKSUM_FUNC_PARSE_REPETITION
uint16_t uniffi_openspd_ffi_checksum_func_parse_repetition(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_CHECKSUM_FUNC_SUMMARIZE
#define UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_CHECKSUM_FUNC_SUMMARIZE
uint16_t uniffi_openspd_ffi_checksum_func_summarize(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_CHECKSUM_FUNC_VELOCITY_LOSS
#define UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_CHECKSUM_FUNC_VELOCITY_LOSS
uint16_t uniffi_openspd_ffi_checksum_func_velocity_loss(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_CHECKSUM_METHOD_LVP_EXERCISE
#define UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_CHECKSUM_METHOD_LVP_EXERCISE
uint16_t uniffi_openspd_ffi_checksum_method_lvp_exercise(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_CHECKSUM_METHOD_LVP_INTERCEPT
#define UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_CHECKSUM_METHOD_LVP_INTERCEPT
uint16_t uniffi_openspd_ffi_checksum_method_lvp_intercept(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_CHECKSUM_METHOD_LVP_IS_VALID
#define UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_CHECKSUM_METHOD_LVP_IS_VALID
uint16_t uniffi_openspd_ffi_checksum_method_lvp_is_valid(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_CHECKSUM_METHOD_LVP_LOAD_FOR_VELOCITY
#define UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_CHECKSUM_METHOD_LVP_LOAD_FOR_VELOCITY
uint16_t uniffi_openspd_ffi_checksum_method_lvp_load_for_velocity(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_CHECKSUM_METHOD_LVP_ONE_RM_KG
#define UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_CHECKSUM_METHOD_LVP_ONE_RM_KG
uint16_t uniffi_openspd_ffi_checksum_method_lvp_one_rm_kg(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_CHECKSUM_METHOD_LVP_PCT_1RM
#define UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_CHECKSUM_METHOD_LVP_PCT_1RM
uint16_t uniffi_openspd_ffi_checksum_method_lvp_pct_1rm(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_CHECKSUM_METHOD_LVP_POINTS
#define UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_CHECKSUM_METHOD_LVP_POINTS
uint16_t uniffi_openspd_ffi_checksum_method_lvp_points(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_CHECKSUM_METHOD_LVP_R2
#define UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_CHECKSUM_METHOD_LVP_R2
uint16_t uniffi_openspd_ffi_checksum_method_lvp_r2(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_CHECKSUM_METHOD_LVP_SLOPE
#define UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_CHECKSUM_METHOD_LVP_SLOPE
uint16_t uniffi_openspd_ffi_checksum_method_lvp_slope(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_CHECKSUM_METHOD_LVP_TO_TEXT
#define UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_CHECKSUM_METHOD_LVP_TO_TEXT
uint16_t uniffi_openspd_ffi_checksum_method_lvp_to_text(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_CHECKSUM_METHOD_LVP_V1RM
#define UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_CHECKSUM_METHOD_LVP_V1RM
uint16_t uniffi_openspd_ffi_checksum_method_lvp_v1rm(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_CHECKSUM_METHOD_LVP_VELOCITY_FOR_PCT
#define UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_CHECKSUM_METHOD_LVP_VELOCITY_FOR_PCT
uint16_t uniffi_openspd_ffi_checksum_method_lvp_velocity_for_pct(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_CHECKSUM_METHOD_REASSEMBLER_PUSH
#define UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_CHECKSUM_METHOD_REASSEMBLER_PUSH
uint16_t uniffi_openspd_ffi_checksum_method_reassembler_push(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_CHECKSUM_CONSTRUCTOR_REASSEMBLER_NEW
#define UNIFFI_FFIDEF_UNIFFI_OPENSPD_FFI_CHECKSUM_CONSTRUCTOR_REASSEMBLER_NEW
uint16_t uniffi_openspd_ffi_checksum_constructor_reassembler_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPENSPD_FFI_UNIFFI_CONTRACT_VERSION
#define UNIFFI_FFIDEF_FFI_OPENSPD_FFI_UNIFFI_CONTRACT_VERSION
uint32_t ffi_openspd_ffi_uniffi_contract_version(void
    
);
#endif

